### ISSUE TITLE
kadd / kdel zsh

### ISSUE THREAD

**Issue by ivomarino** [kubermatic/fubectl#35]
There seems to be parsing issues on `zsh` with `kadd` and `kdel` functions:

```
fubectl.source:69: defining function based on alias `ked'
fubectl.source:69: parse error near `()'
```

when commented out those functions all is fine

**Comment by alexey-anufriev** [comment]
It is not a bug, your problem is related to the fact that those functions are already defined.
I suspect you are using zsh + kubectl plugin. It defines `ked` + `kdel` already.
Just adjust your `fubectl.source` slightly: rename conflicting functions to `kedit` + `kdelete` for example.
