### ISSUE TITLE
Watch a specific namespace

### ISSUE THREAD

**Issue by ghost** [kubermatic/fubectl#40]
`kwall` is really not helpful when trying to monitor a specific namespace, because there's too much information being displayed at once.

The objective here would be to focus on a namespace.

It's an enhancement, is it viable?

**Comment by metalmatze** [comment]
There's is `kwns` which asks you for a namespace to watch and then does exactly what `kwall` is doing.

**Comment by ghost** [comment]
That's awesome, thank you!

This command should probably be documented, it would also be nice to know if there's any other command that may not be documented.
