### ISSUE TITLE
implement kinstall for dependencies

### ISSUE THREAD

**Issue by toschneck** [kubermatic/fubectl#49]
To prevent errors with dependencies like e.g. https://github.com/kubermatic/fubectl/blob/424ad6072c04806003470194b2f3f30ccba00932/fubectl.source#L202
we should implement:
- check if the dependencies are there
- `kinstall` command what installs the needed dependencies

**Comment by scheeles** [comment]
closed by https://github.com/kubermatic/fubectl/pull/54
