### ISSUE TITLE
Consider separate aliases for current NS and all NS

### ISSUE THREAD

**Issue by eshepelyuk** [kubermatic/fubectl#70]
Hello

Currently many aliases are querying resources from all namespaces. In case of big cluster with dozens NS and dozens of pods in evey NS such frequent querying could affect cluster performance and also provide slow response time to end users.

I propose to introduce one of the following
* config parameter (env var, file) that changes namespace filtering behaviour of all declared aliases
* duplicate aliases to have 2 commands 
    * `klog` for current namespace
    * `kloga` for all namespaces
    * For backward compatibility it could be `klog` for current behaviour (all NS) and `klg` for current NS

Wdyt ?

**Comment by eshepelyuk** [comment]
@kron4eg sorry for directly pointing to you, what do you think about the proposal ?

**Comment by kron4eg** [comment]
Probably it will be better not to break existing muscle-memory and create NEW aliases/funcs for current NS only.

**Comment by eshepelyuk** [comment]
So, is the idea in general OK with you ? 
I could provide some example in simple PR soon.

**Comment by kron4eg** [comment]
Yeah, why not :) main point is not changing existing behaviour

**Comment by eshepelyuk** [comment]
> Yeah, why not :) main point is not changing existing behaviour

Deal :)) Will provide sample PR to demonstrate the idea tomorrow.
