### ISSUE TITLE
[proposal] adopt kubectx/kubens

### ISSUE THREAD

**Issue by eshepelyuk** [kubermatic/fubectl#79]
Hello, 

To manage context and namespace switching functionality - kubectx/kubens toolset could be used. 
They could be installed via `krew` as other plugins used by `fubectl`.
`fubectl` could provide useful aliases like `kctx` / `kns`, current context / namespace functions would be deprecated.

Tools homepage: https://github.com/ahmetb/kubectx

**Comment by eshepelyuk** [comment]
@kron4eg thanks a lot for merging #77 
what do you think about this proposal ?

**Comment by kron4eg** [comment]
But we already have `kcs` / `kcns` to switch context / default namespace. I don't see the point.
