### ISSUE TITLE
kdes is not working

### ISSUE THREAD

**Issue by rkondra1** [kubermatic/fubectl#80]
On Mac with zsh kdes is not working and giving below error. Which script mac user have to -- to -I or something like that ? 

_(⎈ |minikube:default)➜  hack git:(master) kdes po
xargs: illegal option -- r
usage: xargs [-0opt] [-E eofstr] [-I replstr [-R replacements]] [-J replstr]
             [-L number] [-n number [-x]] [-P maxprocs] [-s size]
             [utility [argument ...]]
(⎈ |minikube:default)➜  hack git:(master)_

**Comment by kron4eg** [comment]
@rkondra1 which macOS version do you have?

**Comment by rkondra1** [comment]
@kron4eg mac catalina 10.15.7

**Comment by rkondra1** [comment]
I replaced "xargs -r" to xargs and it works for me.
