### ISSUE TITLE
MicroK8s support

### ISSUE THREAD

**Issue by Kehet** [kubermatic/fubectl#88]
[MicroK8S](https://microk8s.io/) is Kubernetes Distribution from Canonical packaged as snap

Since MicroK8s uses proxy command (``microk8s.kubectl get pods`` instead of ``kubectl get pods``) this would require extracting ``kubectl`` command to own variable and maybe some logic like  if ``kubectl`` bin isn't in $PATH then try ``microk8s.kubectl``

I'm willing to submit pull request if this is found useful

**Comment by embik** [comment]
@Kehet, I'm not sure I understand the problem you're facing 100% correctly, but would an alias help you here?

```sh
alias kubectl=microk8s.kubectl
source path/to/fubectl.source
```

I tried this with zsh only, but **if the alias is set before fubectl is sourced/loaded**, it should replace the usage of `kubectl` with `microk8s.kubectl` as is required for you.

**Comment by Kehet** [comment]
Alias indeed would be best option for most users, maybe my use-case (I need multiple kube versions in my job) is bit too specific to be implemented upstream

**Comment by embik** [comment]
I think different kubectl versions is a relatively common use case, so there might be interest in it, I'm just not sure I understand what you're looking for exactly. Falling back to `microk8s.kubectl` when `kubectl` isn't there as a binary is definitely too provider-specific (and kind of a special oddness of microk8s) though.
